GAME_NAME = ""
GAME_VERSION = "0.0.1"
SPRITE_SCALE = 0.02
SCREEN_WIDTH = 1000
SCREEN_HEIGHT = 1000
SPRITE_OFFSET = 10
RADAR_SIZE = 10

ACTION_UP = 'U'
ACTION_DOWN = 'D'
ACTION_LEFT = 'L'
ACTION_RIGHT = 'R'
ACTIONS = [ACTION_UP, ACTION_DOWN, ACTION_LEFT, ACTION_RIGHT]
ACTION_MOVE = {
    ACTION_UP: (0, SPRITE_OFFSET),
    ACTION_DOWN: (0, -SPRITE_OFFSET),
    ACTION_LEFT: (-SPRITE_OFFSET, 0),
    ACTION_RIGHT: (SPRITE_OFFSET, 0)
}

FILE_AGENT = 'agent.al1'


QTABLE_FILE_PATH_J1 = 'data/qtable/qTableJ1VictoryRewardGamma1Alpha0.9'
QTABLE_FILE_PATH_J2 = 'data/qtable/qTableJ2VictoryRewardGamma1Alpha0.9'

BIKE_J1 = "data/assets/boxBlue.png"
BIKE_J2 = "data/assets/boxRed.png"
RADAR_DISPLAY = "data/assets/boxViolet.jpg"

ALPHA = 0.9
GAMMA = 1